//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlovarMVS_07102020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociaciaPerson
    {
        public int id { get; set; }
        public Nullable<int> Slovarid { get; set; }
        public string AssociaciaPerson1 { get; set; }
        public Nullable<int> Person { get; set; }
        public Nullable<int> VotePerson { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual Person Person1 { get; set; }
        public virtual slovar1 slovar1 { get; set; }
    }
}
