//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlovarMVS_07102020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssotsiatsiaMain
    {
        public int id { get; set; }
        public Nullable<int> SlovarId { get; set; }
        public string Assotsiatsia { get; set; }
        public Nullable<int> VoteMain { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual slovar1 slovar1 { get; set; }
    }
}
