//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlovarMVS_07102020.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SlovarEntities : DbContext
    {
        public SlovarEntities()
            : base("name=SlovarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssociaciaPerson> AssociaciaPersons { get; set; }
        public virtual DbSet<AssotsiatsiaMain> AssotsiatsiaMains { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<slovar> slovars { get; set; }
        public virtual DbSet<slovar1> slovar1 { get; set; }
        public virtual DbSet<SlovarPerson> SlovarPersons { get; set; }
        public virtual DbSet<SlovarThema> SlovarThemas { get; set; }
        public virtual DbSet<Thema> Themas { get; set; }
    }
}
