//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlovarMVS_07102020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class slovar
    {
        public int Код { get; set; }
        public string angl { get; set; }
        public string rus { get; set; }
        public string asociacia1 { get; set; }
        public string asociacia2 { get; set; }
        public Nullable<bool> my { get; set; }
        public Nullable<int> thema { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
